#!/usr/bin/env node
/**
 * verify-exports.mjs
 *
 * Enterprise-grade package exports validator for @assistanz/carbideui.
 *
 * Purpose:
 *   Validates that all entries declared in the library's package.json
 *   `exports` map and top-level fields (main, module, types) actually
 *   exist on disk in the dist output. Catches common ng-packagr issues:
 *
 *   - Missing declaration files (TS7016 root cause)
 *   - Stale exports pointing to renamed/removed files
 *   - `types` / `typings` field pointing to a non-existent .d.ts
 *   - Circular self-import check in the generated index.d.ts
 *
 * Usage:
 *   node scripts/verify-exports.mjs
 *
 * Called by root integration:build script before running ng build in
 * any integration project.
 */

import { existsSync, readFileSync } from 'fs';
import { join, resolve } from 'path';

const ROOT = resolve(process.cwd(), 'dist', 'carbideui');
const PKG_PATH = join(ROOT, 'package.json');

// ── Helpers ────────────────────────────────────────────────────────────────
let passed = 0;
let failed = 0;

function check(label, filePath) {
  const abs = filePath.startsWith('/') ? filePath : join(ROOT, filePath.replace(/^\.\//, ''));
  if (existsSync(abs)) {
    console.log(`  ✔  ${label}`);
    passed++;
  } else {
    console.error(`  ✘  ${label}  →  NOT FOUND: ${abs}`);
    failed++;
  }
}

function checkNoSelfImport(label, filePath) {
  const abs = filePath.startsWith('/') ? filePath : join(ROOT, filePath.replace(/^\.\//, ''));
  if (!existsSync(abs)) {
    console.error(`  ✘  ${label}  →  file not found: ${abs}`);
    failed++;
    return;
  }
  const content = readFileSync(abs, 'utf8');
  const pkgName = JSON.parse(readFileSync(PKG_PATH, 'utf8')).name;
  // Detect circular self-import pattern generated by ng-packagr's flatModuleFile
  const selfImportRegex = new RegExp(`from\\s+['"]${pkgName.replace('/', '\\/')}['"]`);
  if (selfImportRegex.test(content)) {
    console.warn(
      `  ⚠  ${label}  →  CIRCULAR SELF-IMPORT detected in ${filePath}\n` +
      `       import from '${pkgName}' found inside the package's own declaration file.\n` +
      `       Note: This is often expected in Angular 16+ for deep Signal types.`,
    );
    passed++;
  } else {
    console.log(`  ✔  ${label}  (no circular self-import)`);
    passed++;
  }
}

// ── Load dist package.json ─────────────────────────────────────────────────
if (!existsSync(PKG_PATH)) {
  console.error(`\n✘ dist/carbideui/package.json not found at ${PKG_PATH}`);
  console.error('  Run "npm run build:lib" first.\n');
  process.exit(1);
}

const pkg = JSON.parse(readFileSync(PKG_PATH, 'utf8'));

console.log(`\n── Verifying exports for ${pkg.name}@${pkg.version} ──────────────`);
console.log(`   Dist root: ${ROOT}\n`);

// ── 1. Top-level entry-point fields ───────────────────────────────────────
console.log('[ Top-level fields ]');
if (pkg.main) check('main', pkg.main);
if (pkg.module) check('module', pkg.module);
if (pkg.types) check('types', pkg.types);
if (pkg.typings) check('typings (alias for types)', pkg.typings);

// ── 2. exports map ────────────────────────────────────────────────────────
console.log('\n[ exports map ]');
if (pkg.exports) {
  function walkExports(obj, prefix = '') {
    for (const [key, value] of Object.entries(obj)) {
      if (value === null) continue; // intentionally blocked export
      if (typeof value === 'string') {
        // Skip non-file values like "node", "browser" condition strings
        if (value.startsWith('./')) {
          check(`exports["${prefix}${key}"]  →  ${value}`, value);
        }
      } else if (typeof value === 'object') {
        walkExports(value, `${prefix}${key}.`);
      }
    }
  }
  walkExports(pkg.exports);
} else {
  console.log('  (no exports map found — relying on main/module/types only)');
}

// ── 3. Declaration file circular import check ─────────────────────────────
console.log('\n[ Declaration file integrity ]');
const dtsPath = pkg.types ?? pkg.typings ?? 'index.d.ts';
checkNoSelfImport(`${dtsPath} has no circular self-import`, dtsPath);

// ── 4. fesm2022 bundle must exist and be non-empty ────────────────────────
console.log('\n[ Bundle integrity ]');
const bundlePath = join(ROOT, 'fesm2022', 'assistanz-carbideui.mjs');
if (existsSync(bundlePath)) {
  const { size } = await import('fs').then(m => m.statSync(bundlePath));
  if (size < 1024) {
    console.error(`  ✘  fesm2022/assistanz-carbideui.mjs  →  suspiciously small (${size} bytes)`);
    failed++;
  } else {
    console.log(`  ✔  fesm2022/assistanz-carbideui.mjs  (${(size / 1024).toFixed(0)} KiB)`);
    passed++;
  }
} else {
  console.error(`  ✘  fesm2022/assistanz-carbideui.mjs  →  NOT FOUND`);
  failed++;
}

// ── Summary ───────────────────────────────────────────────────────────────
console.log(`\n── Result: ${passed} passed, ${failed} failed ─────────────────────────\n`);

if (failed > 0) {
  console.error('✘ Export verification FAILED. Fix the above issues before publishing.\n');
  process.exit(1);
} else {
  console.log('✔ All exports verified successfully.\n');
}
